# Generated by Django 5.1 on 2024-09-04 05:32

import util.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_booking_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(auto_now=True, null=True, validators=[util.model_validators.arrival_date_validator]),
        ),
    ]
