# Generated by Django 5.1 on 2024-09-19 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_booking_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Enter a value in the range 0-30'), django.core.validators.MaxValueValidator(30, 'Enter a value in the range 0-30')]),
        ),
    ]
