# Generated by Django 5.1 on 2024-09-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_booking_children'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
